name: Build Spigot with Latest BuildTools

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'JDK Version for Spigot Build'
        required: true
        default: 17
        type: choice
        options:
        - 8
        - 16
        - 17
      spigot-version:
        description: 'Spigot Version for Build'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04   

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'microsoft'

      - name: Getting BuildTools
        run: curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -o BuildTools.jar
      
      - name: "Building Spigot"
        # !! Change 'latest' to the version what you wanted. !!
        # Also Java version need changing if you're trying building versions below 1.17.X!
        run: "java -jar BuildTools.jar --compile Spigot --rev 1.17.1"

      - name: List Files
        run: ls -al
      
      # Uploading the build jar files.
      - name: "Uploading Built JAR Files"
        uses: "actions/upload-artifact@v2"
        with:
          name: Spigot JAR Files
          path: spigot*.jar

      - name: "Getting Current Date"
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: "Creating Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Spigot ${{ steps.date.outputs.date }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          files: spigot*.jar