name: Build Spigot with Latest BuildTools

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'JDK Version for Spigot Build'
        required: true
        default: 17
        type: choice
        options:
        - 8
        - 16
        - 17
      spigot-version:
        description: 'Spigot Version for Build'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04   

    steps:
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: microsoft

      - name: Getting BuildTools
        run: curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -o BuildTools.jar
      
      - name: Building Spigot ${{ inputs.spigot-version }}
        # !! Change 'latest' to the version what you wanted. !!
        # Also Java version need changing if you're trying building versions below 1.17.X!
        run: java -jar BuildTools.jar --compile Spigot --rev ${{ inputs.spigot-version }}
      
      # Uploading the build jar files.
      - name: Uploading Built JAR Files
        uses: actions/upload-artifact@v2
        with:
          name: Spigot ${{ inputs.spigot-version }} JAR Files
          path: spigot*.jar

      - name: Getting Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Creating Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: Spigot ${{ inputs.spigot-version }} (${{ steps.date.outputs.date }})
          files: spigot*.jar
